# Generated by Django 5.0.2 on 2025-06-02 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='num_speakers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionsegment',
            name='speaker_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'm4a', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='language',
            field=models.CharField(default='en-US', max_length=10),
        ),
    ]
